/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package bus;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.awt.Cursor;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JButton;
import javax.swing.JToggleButton;

/**
 *
 * @author PC
 */
public class seats extends javax.swing.JFrame {

    /**
     * Creates new form seats
     */
    public seats() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton14 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        s19 = new javax.swing.JToggleButton();
        s20 = new javax.swing.JToggleButton();
        s16 = new javax.swing.JToggleButton();
        s13 = new javax.swing.JToggleButton();
        s17 = new javax.swing.JToggleButton();
        s14 = new javax.swing.JToggleButton();
        s10 = new javax.swing.JToggleButton();
        s8 = new javax.swing.JToggleButton();
        s7 = new javax.swing.JToggleButton();
        s11 = new javax.swing.JToggleButton();
        s4 = new javax.swing.JToggleButton();
        s21 = new javax.swing.JToggleButton();
        s18 = new javax.swing.JToggleButton();
        s6 = new javax.swing.JToggleButton();
        s3 = new javax.swing.JToggleButton();
        s12 = new javax.swing.JToggleButton();
        s9 = new javax.swing.JToggleButton();
        s15 = new javax.swing.JToggleButton();
        s1 = new javax.swing.JToggleButton();
        s2 = new javax.swing.JToggleButton();
        s5 = new javax.swing.JToggleButton();
        proceed = new javax.swing.JButton();
        bus_name = new javax.swing.JTextField();

        jToggleButton14.setText("jToggleButton2");

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        s19.setText("19");
        s19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s19ActionPerformed(evt);
            }
        });

        s20.setText("20");
        s20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s20ActionPerformed(evt);
            }
        });

        s16.setText("16");
        s16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s16ActionPerformed(evt);
            }
        });

        s13.setText("13");
        s13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s13ActionPerformed(evt);
            }
        });

        s17.setText("17");
        s17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s17ActionPerformed(evt);
            }
        });

        s14.setText("14");
        s14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s14ActionPerformed(evt);
            }
        });

        s10.setText("10");
        s10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s10ActionPerformed(evt);
            }
        });

        s8.setText("8");
        s8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s8ActionPerformed(evt);
            }
        });

        s7.setText("7");
        s7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s7ActionPerformed(evt);
            }
        });

        s11.setText("11");
        s11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s11ActionPerformed(evt);
            }
        });

        s4.setText("4");
        s4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s4ActionPerformed(evt);
            }
        });

        s21.setText("21");
        s21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s21ActionPerformed(evt);
            }
        });

        s18.setText("18");
        s18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s18ActionPerformed(evt);
            }
        });

        s6.setText("6");
        s6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s6ActionPerformed(evt);
            }
        });

        s3.setText("3");
        s3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s3ActionPerformed(evt);
            }
        });

        s12.setText("12");
        s12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s12ActionPerformed(evt);
            }
        });

        s9.setText("9");
        s9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s9ActionPerformed(evt);
            }
        });

        s15.setText("15");
        s15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s15ActionPerformed(evt);
            }
        });

        s1.setText("1");
        s1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1ActionPerformed(evt);
            }
        });

        s2.setText("2");
        s2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s2ActionPerformed(evt);
            }
        });

        s5.setText("5");
        s5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s5ActionPerformed(evt);
            }
        });

        proceed.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        proceed.setText("PROCEED");
        proceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(proceed, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(88, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bus_name, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(s20, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(s19, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(s21, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(s17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(s16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(s18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(s15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(s12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(s9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(s6))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(s14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(s11))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(s13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(s10)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(s7)
                                    .addComponent(s8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(s4)
                                    .addComponent(s5))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(s1)
                                .addComponent(s2))
                            .addComponent(s3))
                        .addGap(0, 67, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bus_name, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s19)
                    .addComponent(s16)
                    .addComponent(s13)
                    .addComponent(s10)
                    .addComponent(s7)
                    .addComponent(s4)
                    .addComponent(s1))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s20)
                    .addComponent(s17)
                    .addComponent(s14)
                    .addComponent(s11)
                    .addComponent(s8)
                    .addComponent(s2)
                    .addComponent(s5))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s21)
                    .addComponent(s18)
                    .addComponent(s15)
                    .addComponent(s12)
                    .addComponent(s9)
                    .addComponent(s6)
                    .addComponent(s3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(proceed, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void s1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1ActionPerformed
   JToggleButton btn = (JToggleButton) evt.getSource();
    if(btn.isSelected()) {
  
  
        Connection conn;
        String url = "jdbc:mysql://localhost:3306/";
        String dbName="test";
        String driver="com.mysql.jdbc.Driver";
        String userName = "root";
        String password = "ant";
        
        try
        {
         Class.forName(driver);
            conn=(Connection) DriverManager.getConnection(url+dbName,userName,password);    
            java.sql.Statement st=conn.createStatement();
            ResultSet rs=st.executeQuery("select * from cust_info");
            rs.last();
            if(s1.isSelected()) {
                 String b_name = (String)bus_name.getText();
                    int seat_no=1;
                int abc = st.executeUpdate("insert into seats values ('"+b_name+"','"+seat_no+"')");
                
                 int val = st.executeUpdate("SELECT seat_no FROM seats where seat_no = 1)");
                 if(val==1)
                 {
                      new dialog2().setVisible(true);
                 }
                 
            }
                   
           
   }
        catch(Exception e){
            
        }
   }
    }//GEN-LAST:event_s1ActionPerformed

    private void proceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedActionPerformed
        new cust().setVisible(true);
    }//GEN-LAST:event_proceedActionPerformed

    private void s2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s2ActionPerformed
        // TODO add your handling code here:
          JToggleButton btn = (JToggleButton) evt.getSource();
    if(btn.isSelected()) {
  
  
        Connection conn;
        String url = "jdbc:mysql://localhost:3306/";
        String dbName="test";
        String driver="com.mysql.jdbc.Driver";
        String userName = "root";
        String password = "ant";
        
        try
        {
         Class.forName(driver);
            conn=(Connection) DriverManager.getConnection(url+dbName,userName,password);    
            java.sql.Statement st=conn.createStatement();
            ResultSet rs=st.executeQuery("select * from cust_info");
            rs.last();
            if(s2.isSelected()) {
                 String b_name = (String)bus_name.getText();
                    int seat_no=2;
                int abc = st.executeUpdate("insert into seats values ('"+b_name+"','"+seat_no+"')");
                
                 int val = st.executeUpdate("SELECT seat_no FROM seats where seat_no = 2)");
                 if(val==1)
                 {
                      new dialog2().setVisible(true);
                 }
                 
            }
                   
           
   }
        catch(Exception e){
            
        }
   }
       
    }//GEN-LAST:event_s2ActionPerformed

    private void s3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s3ActionPerformed
  JToggleButton btn = (JToggleButton) evt.getSource();
    if(btn.isSelected()) {
  
  
        Connection conn;
        String url = "jdbc:mysql://localhost:3306/";
        String dbName="test";
        String driver="com.mysql.jdbc.Driver";
        String userName = "root";
        String password = "ant";
        
        try
        {
         Class.forName(driver);
            conn=(Connection) DriverManager.getConnection(url+dbName,userName,password);    
            java.sql.Statement st=conn.createStatement();
            ResultSet rs=st.executeQuery("select * from cust_info");
            rs.last();
            if(s3.isSelected()) {
                 String b_name = (String)bus_name.getText();
                    int seat_no=3;
                int abc = st.executeUpdate("insert into seats values ('"+b_name+"','"+seat_no+"')");
                
                 int val = st.executeUpdate("SELECT seat_no FROM seats where seat_no = 3)");
                 if(val==1)
                 {
                      new dialog2().setVisible(true);
                 }
                 
            }
                   
           
   }
        catch(Exception e){
            
        }
   }
         // TODO add your handling code here:
    }//GEN-LAST:event_s3ActionPerformed

    private void s4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s4ActionPerformed
JToggleButton btn = (JToggleButton) evt.getSource();
    if(btn.isSelected()) {
  
  
        Connection conn;
        String url = "jdbc:mysql://localhost:3306/";
        String dbName="test";
        String driver="com.mysql.jdbc.Driver";
        String userName = "root";
        String password = "ant";
        
        try
        {
         Class.forName(driver);
            conn=(Connection) DriverManager.getConnection(url+dbName,userName,password);    
            java.sql.Statement st=conn.createStatement();
            ResultSet rs=st.executeQuery("select * from cust_info");
            rs.last();
            if(s4.isSelected()) {
                 String b_name = (String)bus_name.getText();
                    int seat_no=4;
                int abc = st.executeUpdate("insert into seats values ('"+b_name+"','"+seat_no+"')");
                
                 int val = st.executeUpdate("SELECT seat_no FROM seats where seat_no = 4)");
                 if(val==1)
                 {
                      new dialog2().setVisible(true);
                 }
                 
            }
                   
           
   }
        catch(Exception e){
            
        }
   }        // TODO add your handling code here:
    }//GEN-LAST:event_s4ActionPerformed

    private void s5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s5ActionPerformed
        // TODO add your handling code here:
        JToggleButton btn = (JToggleButton) evt.getSource();
    if(btn.isSelected()) {
  
  
        Connection conn;
        String url = "jdbc:mysql://localhost:3306/";
        String dbName="test";
        String driver="com.mysql.jdbc.Driver";
        String userName = "root";
        String password = "ant";
        
        try
        {
         Class.forName(driver);
            conn=(Connection) DriverManager.getConnection(url+dbName,userName,password);    
            java.sql.Statement st=conn.createStatement();
            ResultSet rs=st.executeQuery("select * from cust_info");
            rs.last();
            if(s5.isSelected()) {
                 String b_name = (String)bus_name.getText();
                    int seat_no=5;
                int abc = st.executeUpdate("insert into seats values ('"+b_name+"','"+seat_no+"')");
                
                 int val = st.executeUpdate("SELECT seat_no FROM seats where seat_no = 5)");
                 if(val==1)
                 {
                      new dialog2().setVisible(true);
                 }
                 
            }
                   
           
   }
        catch(Exception e){
            
        }
   }
    }//GEN-LAST:event_s5ActionPerformed

    private void s6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s6ActionPerformed
    JToggleButton btn = (JToggleButton) evt.getSource();
    if(btn.isSelected()) {
  
  
        Connection conn;
        String url = "jdbc:mysql://localhost:3306/";
        String dbName="test";
        String driver="com.mysql.jdbc.Driver";
        String userName = "root";
        String password = "ant";
        
        try
        {
         Class.forName(driver);
            conn=(Connection) DriverManager.getConnection(url+dbName,userName,password);    
            java.sql.Statement st=conn.createStatement();
            ResultSet rs=st.executeQuery("select * from cust_info");
            rs.last();
            if(s6.isSelected()) {
                 String b_name = (String)bus_name.getText();
                    int seat_no=6;
                int abc = st.executeUpdate("insert into seats values ('"+b_name+"','"+seat_no+"')");
                
                 int val = st.executeUpdate("SELECT seat_no FROM seats where seat_no = 6)");
                 if(val==1)
                 {
                      new dialog2().setVisible(true);
                 }
                 
            }
                   
           
   }
        catch(Exception e){
            
        }
   }       // TODO add your handling code here:
    }//GEN-LAST:event_s6ActionPerformed

    private void s7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s7ActionPerformed
    JToggleButton btn = (JToggleButton) evt.getSource();
    if(btn.isSelected()) {
  
  
        Connection conn;
        String url = "jdbc:mysql://localhost:3306/";
        String dbName="test";
        String driver="com.mysql.jdbc.Driver";
        String userName = "root";
        String password = "ant";
        
        try
        {
         Class.forName(driver);
            conn=(Connection) DriverManager.getConnection(url+dbName,userName,password);    
            java.sql.Statement st=conn.createStatement();
            ResultSet rs=st.executeQuery("select * from cust_info");
            rs.last();
            if(s7.isSelected()) {
                 String b_name = (String)bus_name.getText();
                    int seat_no=7;
                int abc = st.executeUpdate("insert into seats values ('"+b_name+"','"+seat_no+"')");
                
                 int val = st.executeUpdate("SELECT seat_no FROM seats where seat_no = 7)");
                 if(val==1)
                 {
                      new dialog2().setVisible(true);
                 }
                 
            }
                   
           
   }
        catch(Exception e){
            
        }
   }        // TODO add your handling code here:
    }//GEN-LAST:event_s7ActionPerformed

    private void s8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s8ActionPerformed
    JToggleButton btn = (JToggleButton) evt.getSource();
    if(btn.isSelected()) {
  
  
        Connection conn;
        String url = "jdbc:mysql://localhost:3306/";
        String dbName="test";
        String driver="com.mysql.jdbc.Driver";
        String userName = "root";
        String password = "ant";
        
        try
        {
         Class.forName(driver);
            conn=(Connection) DriverManager.getConnection(url+dbName,userName,password);    
            java.sql.Statement st=conn.createStatement();
            ResultSet rs=st.executeQuery("select * from cust_info");
            rs.last();
            if(s8.isSelected()) {
                 String b_name = (String)bus_name.getText();
                    int seat_no=8;
                int abc = st.executeUpdate("insert into seats values ('"+b_name+"','"+seat_no+"')");
                
                 int val = st.executeUpdate("SELECT seat_no FROM seats where seat_no = 8)");
                 if(val==1)
                 {
                      new dialog2().setVisible(true);
                 }
                 
            }
                   
           
   }
        catch(Exception e){
            
        }
   }        // TODO add your handling code here:
    }//GEN-LAST:event_s8ActionPerformed

    private void s9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s9ActionPerformed
    JToggleButton btn = (JToggleButton) evt.getSource();
    if(btn.isSelected()) {
  
  
        Connection conn;
        String url = "jdbc:mysql://localhost:3306/";
        String dbName="test";
        String driver="com.mysql.jdbc.Driver";
        String userName = "root";
        String password = "ant";
        
        try
        {
         Class.forName(driver);
            conn=(Connection) DriverManager.getConnection(url+dbName,userName,password);    
            java.sql.Statement st=conn.createStatement();
            ResultSet rs=st.executeQuery("select * from cust_info");
            rs.last();
            if(s9.isSelected()) {
                 String b_name = (String)bus_name.getText();
                    int seat_no=9;
                int abc = st.executeUpdate("insert into seats values ('"+b_name+"','"+seat_no+"')");
                
                 int val = st.executeUpdate("SELECT seat_no FROM seats where seat_no = 9)");
                 if(val==1)
                 {
                      new dialog2().setVisible(true);
                 }
                 
            }
                   
           
   }
        catch(Exception e){
            
        }
   }        // TODO add your handling code here:
    }//GEN-LAST:event_s9ActionPerformed

    private void s10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s10ActionPerformed
    JToggleButton btn = (JToggleButton) evt.getSource();
    if(btn.isSelected()) {
  
  
        Connection conn;
        String url = "jdbc:mysql://localhost:3306/";
        String dbName="test";
        String driver="com.mysql.jdbc.Driver";
        String userName = "root";
        String password = "ant";
        
        try
        {
         Class.forName(driver);
            conn=(Connection) DriverManager.getConnection(url+dbName,userName,password);    
            java.sql.Statement st=conn.createStatement();
            ResultSet rs=st.executeQuery("select * from cust_info");
            rs.last();
            if(s10.isSelected()) {
                 String b_name = (String)bus_name.getText();
                    int seat_no=10;
                int abc = st.executeUpdate("insert into seats values ('"+b_name+"','"+seat_no+"')");
                
                 int val = st.executeUpdate("SELECT seat_no FROM seats where seat_no = 10)");
                 if(val==1)
                 {
                      new dialog2().setVisible(true);
                 }
                 
            }
                   
           
   }
        catch(Exception e){
            
        }
   }        // TODO add your handling code here:
    }//GEN-LAST:event_s10ActionPerformed

    private void s11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s11ActionPerformed
    JToggleButton btn = (JToggleButton) evt.getSource();
    if(btn.isSelected()) {
  
  
        Connection conn;
        String url = "jdbc:mysql://localhost:3306/";
        String dbName="test";
        String driver="com.mysql.jdbc.Driver";
        String userName = "root";
        String password = "ant";
        
        try
        {
         Class.forName(driver);
            conn=(Connection) DriverManager.getConnection(url+dbName,userName,password);    
            java.sql.Statement st=conn.createStatement();
            ResultSet rs=st.executeQuery("select * from cust_info");
            rs.last();
            if(s11.isSelected()) {
                 String b_name = (String)bus_name.getText();
                    int seat_no=11;
                int abc = st.executeUpdate("insert into seats values ('"+b_name+"','"+seat_no+"')");
                
                 int val = st.executeUpdate("SELECT seat_no FROM seats where seat_no = 11)");
                 if(val==1)
                 {
                      new dialog2().setVisible(true);
                 }
                 
            }
                   
           
   }
        catch(Exception e){
            
        }
   }        // TODO add your handling code here:
    }//GEN-LAST:event_s11ActionPerformed

    private void s12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s12ActionPerformed
    JToggleButton btn = (JToggleButton) evt.getSource();
    if(btn.isSelected()) {
  
  
        Connection conn;
        String url = "jdbc:mysql://localhost:3306/";
        String dbName="test";
        String driver="com.mysql.jdbc.Driver";
        String userName = "root";
        String password = "ant";
        
        try
        {
         Class.forName(driver);
            conn=(Connection) DriverManager.getConnection(url+dbName,userName,password);    
            java.sql.Statement st=conn.createStatement();
            ResultSet rs=st.executeQuery("select * from cust_info");
            rs.last();
            if(s12.isSelected()) {
                 String b_name = (String)bus_name.getText();
                    int seat_no=12;
                int abc = st.executeUpdate("insert into seats values ('"+b_name+"','"+seat_no+"')");
                
                 int val = st.executeUpdate("SELECT seat_no FROM seats where seat_no = 12)");
                 if(val==1)
                 {
                      new dialog2().setVisible(true);
                 }
                 
            }
                   
           
   }
        catch(Exception e){
            
        }
   }        // TODO add your handling code here:
    }//GEN-LAST:event_s12ActionPerformed

    private void s13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s13ActionPerformed
    JToggleButton btn = (JToggleButton) evt.getSource();
    if(btn.isSelected()) {
  
  
        Connection conn;
        String url = "jdbc:mysql://localhost:3306/";
        String dbName="test";
        String driver="com.mysql.jdbc.Driver";
        String userName = "root";
        String password = "ant";
        
        try
        {
         Class.forName(driver);
            conn=(Connection) DriverManager.getConnection(url+dbName,userName,password);    
            java.sql.Statement st=conn.createStatement();
            ResultSet rs=st.executeQuery("select * from cust_info");
            rs.last();
            if(s13.isSelected()) {
                 String b_name = (String)bus_name.getText();
                    int seat_no=13;
                int abc = st.executeUpdate("insert into seats values ('"+b_name+"','"+seat_no+"')");
                
                 int val = st.executeUpdate("SELECT seat_no FROM seats where seat_no = 12)");
                 if(val==1)
                 {
                      new dialog2().setVisible(true);
                 }
                 
            }
                   
           
   }
        catch(Exception e){
            
        }
   }        // TODO add your handling code here:
    }//GEN-LAST:event_s13ActionPerformed

    private void s14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s14ActionPerformed
    JToggleButton btn = (JToggleButton) evt.getSource();
    if(btn.isSelected()) {
  
  
        Connection conn;
        String url = "jdbc:mysql://localhost:3306/";
        String dbName="test";
        String driver="com.mysql.jdbc.Driver";
        String userName = "root";
        String password = "ant";
        
        try
        {
         Class.forName(driver);
            conn=(Connection) DriverManager.getConnection(url+dbName,userName,password);    
            java.sql.Statement st=conn.createStatement();
            ResultSet rs=st.executeQuery("select * from cust_info");
            rs.last();
            if(s14.isSelected()) {
                 String b_name = (String)bus_name.getText();
                    int seat_no=14;
                int abc = st.executeUpdate("insert into seats values ('"+b_name+"','"+seat_no+"')");
                
                 int val = st.executeUpdate("SELECT seat_no FROM seats where seat_no = 14)");
                 if(val==1)
                 {
                      new dialog2().setVisible(true);
                 }
                 
            }
                   
           
   }
        catch(Exception e){
            
        }
   }        // TODO add your handling code here:
    }//GEN-LAST:event_s14ActionPerformed

    private void s15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s15ActionPerformed
    JToggleButton btn = (JToggleButton) evt.getSource();
    if(btn.isSelected()) {
  
  
        Connection conn;
        String url = "jdbc:mysql://localhost:3306/";
        String dbName="test";
        String driver="com.mysql.jdbc.Driver";
        String userName = "root";
        String password = "ant";
        
        try
        {
         Class.forName(driver);
            conn=(Connection) DriverManager.getConnection(url+dbName,userName,password);    
            java.sql.Statement st=conn.createStatement();
            ResultSet rs=st.executeQuery("select * from cust_info");
            rs.last();
            if(s15.isSelected()) {
                 String b_name = (String)bus_name.getText();
                    int seat_no=15;
                int abc = st.executeUpdate("insert into seats values ('"+b_name+"','"+seat_no+"')");
                
                 int val = st.executeUpdate("SELECT seat_no FROM seats where seat_no = 15)");
                 if(val==1)
                 {
                      new dialog2().setVisible(true);
                 }
                 
            }
                   
           
   }
        catch(Exception e){
            
        }
   }        // TODO add your handling code here:
    }//GEN-LAST:event_s15ActionPerformed

    private void s16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s16ActionPerformed
    JToggleButton btn = (JToggleButton) evt.getSource();
    if(btn.isSelected()) {
  
  
        Connection conn;
        String url = "jdbc:mysql://localhost:3306/";
        String dbName="test";
        String driver="com.mysql.jdbc.Driver";
        String userName = "root";
        String password = "ant";
        
        try
        {
         Class.forName(driver);
            conn=(Connection) DriverManager.getConnection(url+dbName,userName,password);    
            java.sql.Statement st=conn.createStatement();
            ResultSet rs=st.executeQuery("select * from cust_info");
            rs.last();
            if(s16.isSelected()) {
                 String b_name = (String)bus_name.getText();
                    int seat_no=16;
                int abc = st.executeUpdate("insert into seats values ('"+b_name+"','"+seat_no+"')");
                
                 int val = st.executeUpdate("SELECT seat_no FROM seats where seat_no = 16)");
                 if(val==1)
                 {
                      new dialog2().setVisible(true);
                 }
                 
            }
                   
           
   }
        catch(Exception e){
            
        }
   }        // TODO add your handling code here:
    }//GEN-LAST:event_s16ActionPerformed

    private void s17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s17ActionPerformed
    JToggleButton btn = (JToggleButton) evt.getSource();
    if(btn.isSelected()) {
  
  
        Connection conn;
        String url = "jdbc:mysql://localhost:3306/";
        String dbName="test";
        String driver="com.mysql.jdbc.Driver";
        String userName = "root";
        String password = "ant";
        
        try
        {
         Class.forName(driver);
            conn=(Connection) DriverManager.getConnection(url+dbName,userName,password);    
            java.sql.Statement st=conn.createStatement();
            ResultSet rs=st.executeQuery("select * from cust_info");
            rs.last();
            if(s17.isSelected()) {
                 String b_name = (String)bus_name.getText();
                    int seat_no=17;
                int abc = st.executeUpdate("insert into seats values ('"+b_name+"','"+seat_no+"')");
                
                 int val = st.executeUpdate("SELECT seat_no FROM seats where seat_no = 17)");
                 if(val==1)
                 {
                      new dialog2().setVisible(true);
                 }
                 
            }
                   
           
   }
        catch(Exception e){
            
        }
   }        // TODO add your handling code here:
    }//GEN-LAST:event_s17ActionPerformed

    private void s18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s18ActionPerformed
    JToggleButton btn = (JToggleButton) evt.getSource();
    if(btn.isSelected()) {
  
  
        Connection conn;
        String url = "jdbc:mysql://localhost:3306/";
        String dbName="test";
        String driver="com.mysql.jdbc.Driver";
        String userName = "root";
        String password = "ant";
        
        try
        {
         Class.forName(driver);
            conn=(Connection) DriverManager.getConnection(url+dbName,userName,password);    
            java.sql.Statement st=conn.createStatement();
            ResultSet rs=st.executeQuery("select * from cust_info");
            rs.last();
            if(s18.isSelected()) {
                 String b_name = (String)bus_name.getText();
                    int seat_no=18;
                int abc = st.executeUpdate("insert into seats values ('"+b_name+"','"+seat_no+"')");
                
                 int val = st.executeUpdate("SELECT seat_no FROM seats where seat_no = 18)");
                 if(val==1)
                 {
                      new dialog2().setVisible(true);
                 }
                 
            }
                   
           
   }
        catch(Exception e){
            
        }
   }        // TODO add your handling code here:
    }//GEN-LAST:event_s18ActionPerformed

    private void s19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s19ActionPerformed
    JToggleButton btn = (JToggleButton) evt.getSource();
    if(btn.isSelected()) {
  
  
        Connection conn;
        String url = "jdbc:mysql://localhost:3306/";
        String dbName="test";
        String driver="com.mysql.jdbc.Driver";
        String userName = "root";
        String password = "ant";
        
        try
        {
         Class.forName(driver);
            conn=(Connection) DriverManager.getConnection(url+dbName,userName,password);    
            java.sql.Statement st=conn.createStatement();
            ResultSet rs=st.executeQuery("select * from cust_info");
            rs.last();
            if(s19.isSelected()) {
                 String b_name = (String)bus_name.getText();
                    int seat_no=19;
                int abc = st.executeUpdate("insert into seats values ('"+b_name+"','"+seat_no+"')");
                
                 int val = st.executeUpdate("SELECT seat_no FROM seats where seat_no = 19)");
                 if(val==1)
                 {
                      new dialog2().setVisible(true);
                 }
                 
            }
                   
           
   }
        catch(Exception e){
            
        }
   }        // TODO add your handling code here:
    }//GEN-LAST:event_s19ActionPerformed

    private void s20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s20ActionPerformed
    JToggleButton btn = (JToggleButton) evt.getSource();
    if(btn.isSelected()) {
  
  
        Connection conn;
        String url = "jdbc:mysql://localhost:3306/";
        String dbName="test";
        String driver="com.mysql.jdbc.Driver";
        String userName = "root";
        String password = "ant";
        
        try
        {
         Class.forName(driver);
            conn=(Connection) DriverManager.getConnection(url+dbName,userName,password);    
            java.sql.Statement st=conn.createStatement();
            ResultSet rs=st.executeQuery("select * from cust_info");
            rs.last();
            if(s20.isSelected()) {
                 String b_name = (String)bus_name.getText();
                    int seat_no=20;
                int abc = st.executeUpdate("insert into seats values ('"+b_name+"','"+seat_no+"')");
                
                 int val = st.executeUpdate("SELECT seat_no FROM seats where seat_no = 20)");
                 if(val==1)
                 {
                      new dialog2().setVisible(true);
                 }
                 
            }
                   
           
   }
        catch(Exception e){
            
        }
   }        // TODO add your handling code here:
    }//GEN-LAST:event_s20ActionPerformed

    private void s21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s21ActionPerformed
    JToggleButton btn = (JToggleButton) evt.getSource();
    if(btn.isSelected()) {
  
  
        Connection conn;
        String url = "jdbc:mysql://localhost:3306/";
        String dbName="test";
        String driver="com.mysql.jdbc.Driver";
        String userName = "root";
        String password = "ant";
        
        try
        {
         Class.forName(driver);
            conn=(Connection) DriverManager.getConnection(url+dbName,userName,password);    
            java.sql.Statement st=conn.createStatement();
            ResultSet rs=st.executeQuery("select * from cust_info");
            rs.last();
            if(s2.isSelected()) {
                 String b_name = (String)bus_name.getText();
                    int seat_no=21;
                int abc = st.executeUpdate("insert into seats values ('"+b_name+"','"+seat_no+"')");
                
                 int val = st.executeUpdate("SELECT seat_no FROM seats where seat_no = 21)");
                 if(val==1)
                 {
                      new dialog2().setVisible(true);
                 }
                 
            }
                   
           
   }
        catch(Exception e){
            
        }
   }        // TODO add your handling code here:
    }//GEN-LAST:event_s21ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(seats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(seats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(seats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(seats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new seats().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bus_name;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToggleButton jToggleButton14;
    private javax.swing.JButton proceed;
    private javax.swing.JToggleButton s1;
    private javax.swing.JToggleButton s10;
    private javax.swing.JToggleButton s11;
    private javax.swing.JToggleButton s12;
    private javax.swing.JToggleButton s13;
    private javax.swing.JToggleButton s14;
    private javax.swing.JToggleButton s15;
    private javax.swing.JToggleButton s16;
    private javax.swing.JToggleButton s17;
    private javax.swing.JToggleButton s18;
    private javax.swing.JToggleButton s19;
    private javax.swing.JToggleButton s2;
    private javax.swing.JToggleButton s20;
    private javax.swing.JToggleButton s21;
    private javax.swing.JToggleButton s3;
    private javax.swing.JToggleButton s4;
    private javax.swing.JToggleButton s5;
    private javax.swing.JToggleButton s6;
    private javax.swing.JToggleButton s7;
    private javax.swing.JToggleButton s8;
    private javax.swing.JToggleButton s9;
    // End of variables declaration//GEN-END:variables
}
